config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
    - "*/.DS_Store"
dotfiles:
  f_inputrc:
    dst: ~/.inputrc
    src: .inputrc
  f_vimrc:
    dst: ~/.vimrc
    src: .vimrc
  d_zsh_custom:
    dst: ~/.oh-my-zsh/custom
    src: .oh-my-zsh/custom
profiles:
  home:
    dotfiles:
      - f_inputrc
      - f_vimrc
      - d_zsh_custom
