config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
    - ".DS_Store"
  instignore:
    - ".DS_Store"
dotfiles:
  d_gnupg:
    src: .gnupg
    dst: ~/.gnupg
    chmod: 700
  d_hammerspoon:
    src: .hammerspoon
    dst: ~/.hammerspoon
  d_zsh_custom:
    src: .oh-my-zsh/custom
    dst: ~/.oh-my-zsh/custom
  f_daily:
    src: .local/bin/daily
    dst: ~/.local/bin/daily
    chmod: 755
  f_today:
    src: .local/bin/today
    dst: ~/.local/bin/today
    chmod: 755
  f_inputrc:
    src: .inputrc
    dst: ~/.inputrc
  f_vimrc:
    src: .vimrc
    dst: ~/.vimrc
  f_Brewfile:
    src: Brewfile
    dst: ~/Brewfile
profiles:
  # home
  w-mbp.local:
    dotfiles:
      - d_zsh_custom
      - f_daily
      - f_today
      - f_inputrc
      - f_vimrc
      - f_Brewfile

  # work
  w-mbp-work.local:
    dotfiles:
      - d_zsh_custom
      - d_hammerspoon
      - f_daily
      - f_today
      - f_inputrc
      - f_vimrc
      - f_Brewfile
