config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
    - ".DS_Store"
  instignore:
    - ".DS_Store"
dotfiles:
  d_hammerspoon:
    src: .hammerspoon
    dst: ~/.hammerspoon
  d_zsh_custom:
    src: .oh-my-zsh/custom
    dst: ~/.oh-my-zsh/custom
  f_command_helper:
    src: bin/command_helper.sh
    dst: ~/bin/command_helper.sh
    chmod: 755
  f_daily:
    src: bin/daily
    dst: ~/bin/daily
    chmod: 755
  f_today:
    src: bin/today
    dst: ~/bin/today
    chmod: 755
  f_inputrc:
    src: .inputrc
    dst: ~/.inputrc
  f_vimrc:
    src: .vimrc
    dst: ~/.vimrc
  f_Brewfile:
    src: Brewfile
    dst: ~/Brewfile
profiles:
  # home
  WheredeMacBook-Pro.local:
    dotfiles:
      - d_hammerspoon
      - d_zsh_custom
      - f_command_helper
      - f_daily
      - f_today
      - f_inputrc
      - f_vimrc
      - f_Brewfile

  # work
  wheredeMacBook-Pro-2.local:
    dotfiles:
      - d_hammerspoon
      - d_zsh_custom
      - f_command_helper
      - f_daily
      - f_today
      - f_inputrc
      - f_vimrc
      - f_Brewfile
